<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="view/css/style.css">
    <script src="view/js/jquery.js"></script>
    <title>Titre</title>
</head>

<body>
    <nav>
        <ul>
            <li><a href="index.php?page=home">acceuil</a></li>
            <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
                <li><a href="index.php?page=friends_list&amp;id=<?= $_SESSION['id'] ?>">follow</a></li>
                <li><a class="user_session" href="index.php?page=profil&amp;id=<?= $_SESSION['id'] ?>" value="<?= $_SESSION['id'] ?>">profil</a></li>
                <li class="post_nav_button">poster</li>
            <?php else : ?>
                <li><a href="index.php?page=connexion_page">connexion</a></li>
                <li><a href="index.php?page=create_account_page">créer un compte</a></li>
            <?php endif; ?>
        </ul>
    </nav>
    <main>
        <?php include $template . ".phtml"; ?>
    </main>
    <script src="view/js/script.js"></script>
    <noscript>Your browser does not support JavaScript!</noscript>
</body>

</html>