<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="view/js/jquery.js"></script>
    <link rel="stylesheet" href="view/css/style.css">
    <title>title</title>
</head>

<body>
    <main>
        <?php include $template . ".phtml"; ?>
    </main>

    <script src="view/js/script.js"></script>
</body>

</html>